### ISSUE TITLE
Review Submission

### ISSUE THREAD

**Issue by not-xygen** [Chuu04/Proyek-Web-PCDB#1]
### Hi, Cinta

Disini ada beberapa kesalahan nih.

1. Struktur kodenya masih salah nih, seharusnya begini yah
```html
<main>
 <div id=content>
  <aside>...</aside>
  <section id="description">...</section>
  <section id="article">...</section>
  <section id="form">...</section>
  ...
 </div>
</main>
```
di kode kamu, form diluar `div id="content"`, bisa dipindah ke dalamnya lalu `div id="form"` diganti menjadi `section id="form"` yah
 
2. elemen `script` bisa dipindah kesebelum penutup tag `body` yah

Mungkin itu saja dari revisiannya, ada beberapa yang opsional kamu bisa implementasikan:
1. karena kamu sudah ada CSS, kamu bisa menghapus elemen `style` lalu bisa memindahkan isi `style` kedalam CSS
2. JavaScriptnya bisa dirapihin agar alertnya muncul. yang `value` dihapus saja di alert dan deklarasi variablenya

Mungkin itu saja untuk revisinya, ditunggu, jangan lupa upload ulang di repository ini dan komen dibawah ya, Terimakasih!

**Comment by Chuu04** [comment]
Cinta Satilla - 11221071 - https://github.com/Chuu04/Proyek-Web-PCDB.git

**Comment by not-xygen** [comment]
## Halo,

Jadi strukturnya sudah bener, tapi kurang satu aja lagi. Seharusnya aside diluar `<div id="content">`:
```html
<main>
 <aside>...</aside>
 <div id="content">...</div>
</main>
```

Dibaikin ya, tapi aku approve untuk submissionnya. Thanks dan goodluck CSS nya nanti!

**Comment by Chuu04** [comment]
Cinta Satilla - 11221071 - https://github.com/Chuu04/Proyek-Web-PCDB.git

**Comment by not-xygen** [comment]
Oke terimakasih, submission approved!
